// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAn7sbuik3NQp_QGchBUbQ5JgYH6UHSZCU',
    appId: '1:963550308940:ios:f60e6c45cc734da9c9a2e9',
    messagingSenderId: '963550308940',
    projectId: 'fras-3b491',
    storageBucket: 'fras-3b491.appspot.com',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAn7sbuik3NQp_QGchBUbQ5JgYH6UHSZCU',
    appId: '1:963550308940:ios:f60e6c45cc734da9c9a2e9',
    messagingSenderId: '963550308940',
    projectId: 'fras-3b491',
    storageBucket: 'fras-3b491.appspot.com',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSeAzI5OsLrbRdtbiawy3u1vBKa2R5uEk',
    appId: '1:963550308940:web:83180c1332c5d5c7c9a2e9',
    messagingSenderId: '963550308940',
    projectId: 'fras-3b491',
    authDomain: 'fras-3b491.firebaseapp.com',
    storageBucket: 'fras-3b491.appspot.com',
    measurementId: 'G-QG1ED28W61',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtmN0hEGj1XN4i3e_k_cwMgxGVSXfIQ2Y',
    appId: '1:963550308940:android:b4a04ceac2e7eee0c9a2e9',
    messagingSenderId: '963550308940',
    projectId: 'fras-3b491',
    storageBucket: 'fras-3b491.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDSeAzI5OsLrbRdtbiawy3u1vBKa2R5uEk',
    appId: '1:963550308940:web:f7f501b5ca942d43c9a2e9',
    messagingSenderId: '963550308940',
    projectId: 'fras-3b491',
    authDomain: 'fras-3b491.firebaseapp.com',
    storageBucket: 'fras-3b491.appspot.com',
    measurementId: 'G-DLR924ZN2Z',
  );

}